In [24]:
import numpy as np

In [25]:
y = np.array([1,2,3,4,5])
print(np.sum(y - np.mean(y)))

0.0


In [28]:
y.shape

(5,)

In [27]:
y.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
y.shape

(5,)

In [18]:
print(np.sum(y - np.mean(y)))

0.0


In [23]:
np.dot(2, y) + 5

array([[ 7],
       [ 9],
       [11],
       [13],
       [15]])

In [105]:
X = np.array([[7, 12,16], [21,25, 56], [23, 45, 87]])

In [106]:
# from sklearn import datasets
# X, y = datasets.make_regression(n_samples=10, n_features=3, noise= 50, random_state= 31)


In [107]:
X

array([[ 7, 12, 16],
       [21, 25, 56],
       [23, 45, 87]])

In [108]:
X.T

array([[ 7, 21, 23],
       [12, 25, 45],
       [16, 56, 87]])

In [109]:
np.mean(X.T)

np.float64(32.44444444444444)

In [110]:
np.mean(X.T, axis = 1)


array([17.        , 27.33333333, 53.        ])

In [111]:
# np.sum(X - np.mean(X.T, axis= 1))
print(X- np.mean(X.T, axis= 1))

[[-10.         -15.33333333 -37.        ]
 [  4.          -2.33333333   3.        ]
 [  6.          17.66666667  34.        ]]


In [112]:
X - np.mean(X.T, axis= 1)

array([[-10.        , -15.33333333, -37.        ],
       [  4.        ,  -2.33333333,   3.        ],
       [  6.        ,  17.66666667,  34.        ]])

In [113]:
np.sum(X - np.mean(X.T, axis= 1), axis= 0)

array([0.00000000e+00, 3.55271368e-15, 0.00000000e+00])

In [114]:
np.sum(y - np.mean(y)) / np.sum(X - np.mean(X.T, axis= 1), axis= 0)

C:\Users\spurusho\AppData\Local\Temp\ipykernel_13060\2813919610.py:1: RuntimeWarning: divide by zero encountered in divide
  np.sum(y - np.mean(y)) / np.sum(X - np.mean(X.T, axis= 1), axis= 0)


array([inf, 24., inf])

In [58]:
m  = np.sum(y - np.mean(y)) / np.sum(X - np.mean(X.T, axis= 1), axis=1)

In [67]:
m

array([-1.89478063e-14,  1.89478063e-14])

In [61]:
np.mean(X.T, axis= 1)

array([2.5, 3.5, 4.5])

In [59]:
np.dot(m * np.mean(X.T, axis= 1))

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [43]:
y.mean()

np.float64(-34.22467142653187)

In [38]:
np.sum(X.T - np.mean(X))

np.float64(5.551115123125783e-16)

In [37]:
np.sum(X.T - np.mean(X.T))

np.float64(5.551115123125783e-16)